<!-- Link Social Media 
{% style "css/social/bootstrap-social.css" %}
{% style "css/social/assets/css/font-awesome.css" %}
-->

<!-- 
<div class="social-buttons" style="display: inline-block; float: right;">
        <a href="https://github.com/DomainDrivenArchitecture" class="btn btn-social-icon btn-github" onclick="_gaq.push(['_trackEvent', 'btn-social-icon', 'click', 'btn-adn']);"><span class="fab fa-github"></span></a>
        <a href="http://stackoverflow.com/users/3405078/jerger" class="btn btn-social-icon btn-bitbucket" onclick="_gaq.push(['_trackEvent', 'btn-social-icon', 'click', 'btn-bitbucket']);"><span class="fab fa-stack-overflow"></span></a>
        <a href="https://www.xing.com/profile/Michael_Jerger" class="btn btn-social-icon btn-dropbox" onclick="_gaq.push(['_trackEvent', 'btn-social-icon', 'click', 'btn-dropbox']);"><span class="fab fa-xing"></span></a>
        <a href="https://www.linkedin.com/in/michael-jerger-805432" class="btn btn-social-icon btn-linkedin" onclick="_gaq.push(['_trackEvent', 'btn-social-icon', 'click', 'btn-facebook']);"><span class="fab fa-linkedin"></span></a>
</div>
 -->
