<!-- Link Social Media -->
<div class="social-buttons" style="display: inline-block; float: right;">
        <a title="GitHub" href="..." rel="external">
                <span class="fab fa-github text-white"></span></a>
        <a title="Mastodon" href="..." rel="external">
                <span class="fab fa-mastodon text-white"></span></a>
        <a title="Stack Overflow" href="..." rel="external">
                <span class="fab fa-stack-overflow text-white"></span></a>
        <a title="Xing" href="..." rel="external">
        <span class="fab fa-xing text-white"></span></a>
        <a title="LinkedIn" href="..." rel="external">
                <span class="fab fa-linkedin text-white"></span></a>
</div>

