<h3 style="text-align: center;">Partner</h1>
<p style="text-align: center;">
	<a href="http://www.osb-alliance.de" target="_blank"> <img
		alt="Open Source Business Alliance" class="partner_image_center"
		src="/img/meissa/Member_OSB_final.png"
		style="width: 101px; height: 50px;"></a>
</p>
<p style="text-align: center;">
	<a href="http://www.senioren-der-wirtschaft.de/" target="_blank"><img
		class="partner_image_center" name="Senioren der Wirtschaft"
		src="/img/meissa/Senioren_der_Wirtschaft_Logo_RGB_s.jpg"
		style="height: 41px; width: 107px;"></a>
</p>
