<h3 class="text-center">Wir unterstützen</h3>
<p>&nbsp;</p>
<p class="text-center">
	<a href="https://www.politaktiv.org/" target="_blank"><img
		class="text-center" name="https://www.politaktiv.org/"
		src="/img/meissa/politaktiv.png"
		style="width: 99px; height: 50px;"></a>
</p>
<p class="text-center">
	<a href="https://fsfe.org/donate/thankgnus.de.html" target="_blank"><img
		class="partner_image_center" name="fsfe.org"
		src="/img/meissa/fsfe.png"
		style="height: 71px; width: 107px;"></a>
</p>
<p class="text-center">
	<a href="http://wilhelmtux.ch/?MID=10&amp;PID=90#list" target="_blank"><img
		class="partner_image_center" name="wilhelmtux.ch"
		src="/img/meissa/tux.gif"
		style="height: 84px; width: 76px;"></a>
</p>